version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geo_match_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geo_match_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: 11211
    depends_on:
      - postgres
      - memcached
    ports:
      - "8080:8080"  # Если потребуется веб-сервер или другой доступ извне

volumes:
  postgres_data:
